name: Deploy to build branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to build branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://npm.pkg.github.com

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Create CNAME
        uses: finnp/create-file-action@master
        env:
          FILE_NAME: "dist/CNAME"
          FILE_DATA: "kakizome.online"

      - name: Deploy
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: self
          BRANCH: build
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
